version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file: ".env"
    depends_on:
      - db

  db:
    image: postgres:15
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - gamestats-db-data:/var/lib/postgresql/data

volumes:
  gamestats-db-data:
