spring:
  application:
    name: gamestats
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: ${PORT}
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET}
