CREATE TABLE characters
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version                BIGINT,
    script_tool_identifier VARCHAR(255),
    name                   VARCHAR(255),
    character_type         VARCHAR(255),
    wiki_page_link         VARCHAR(255),
    image_url              VARCHAR(255),
    CONSTRAINT pk_characters PRIMARY KEY (id)
);

CREATE TABLE game_storytellers
(
    game_id   BIGINT NOT NULL,
    player_id BIGINT NOT NULL
);

CREATE TABLE game_winning_players
(
    game_id   BIGINT NOT NULL,
    player_id BIGINT NOT NULL
);

CREATE TABLE games
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version           BIGINT,
    script_id         BIGINT                                  NOT NULL,
    winning_alignment VARCHAR(255),
    description       VARCHAR(255),
    name              VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_games PRIMARY KEY (id)
);

CREATE TABLE player_participations
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version              BIGINT,
    game_id              BIGINT,
    player_id            BIGINT,
    initial_character_id BIGINT,
    initial_alignment    VARCHAR(255),
    end_character_id     BIGINT,
    end_alignment        VARCHAR(255),
    is_alive_at_end      BOOLEAN                                 NOT NULL,
    participant_order    INTEGER,
    CONSTRAINT pk_player_participations PRIMARY KEY (id)
);

CREATE TABLE players
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version  BIGINT,
    name     VARCHAR(255),
    owner_id BIGINT,
    CONSTRAINT pk_players PRIMARY KEY (id)
);

CREATE TABLE script_characters
(
    character_id BIGINT NOT NULL,
    script_id    BIGINT NOT NULL
);

CREATE TABLE scripts
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT,
    name           VARCHAR(255),
    wiki_page_link VARCHAR(255),
    description    VARCHAR(255),
    CONSTRAINT pk_scripts PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version  BIGINT,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    role     VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE players
    ADD CONSTRAINT uc_players_owner UNIQUE (owner_id);

ALTER TABLE game_storytellers
    ADD CONSTRAINT FK_GAME_STORYTELLERS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE game_storytellers
    ADD CONSTRAINT FK_GAME_STORYTELLERS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE games
    ADD CONSTRAINT FK_GAMES_ON_SCRIPT FOREIGN KEY (script_id) REFERENCES scripts (id) ON DELETE SET NULL;

ALTER TABLE players
    ADD CONSTRAINT FK_PLAYERS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE SET NULL;

ALTER TABLE player_participations
    ADD CONSTRAINT FK_PLAYER_PARTICIPATIONS_ON_ENDCHARACTER FOREIGN KEY (end_character_id) REFERENCES characters (id) ON DELETE SET NULL;

ALTER TABLE player_participations
    ADD CONSTRAINT FK_PLAYER_PARTICIPATIONS_ON_GAME FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE player_participations
    ADD CONSTRAINT FK_PLAYER_PARTICIPATIONS_ON_INITIALCHARACTER FOREIGN KEY (initial_character_id) REFERENCES characters (id) ON DELETE SET NULL;

ALTER TABLE player_participations
    ADD CONSTRAINT FK_PLAYER_PARTICIPATIONS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES players (id) ON DELETE SET NULL;

ALTER TABLE game_winning_players
    ADD CONSTRAINT GMbZz2 FOREIGN KEY (game_id) REFERENCES games (id);

ALTER TABLE script_characters
    ADD CONSTRAINT X9brKa FOREIGN KEY (character_id) REFERENCES characters (id);

ALTER TABLE game_winning_players
    ADD CONSTRAINT dUMLCI FOREIGN KEY (player_id) REFERENCES players (id);

ALTER TABLE script_characters
    ADD CONSTRAINT twcjxL FOREIGN KEY (script_id) REFERENCES scripts (id);
